#!/usr/bin/env bash
# Generate /opt/c2k/.env.production on first deploy. Safe to re-run (won't overwrite existing).
set -euo pipefail

ROOT="${1:-/opt/c2k}"
ENV_FILE="$ROOT/.env.production"
DOMAIN="${DOMAIN:-kink.social}"

rand() {
  openssl rand -hex 32
}

rand24() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

if [[ -f "$ENV_FILE" ]]; then
  echo ".env.production already exists — skipping generation."
  exit 0
fi

POSTGRES_PASSWORD="$(rand24)"
AUTH_SECRET="$(rand)"
COOKIE_SECRET="$(rand)"
FIELD_KEY="$(rand)"
EMAIL_PEPPER="$(rand)"
EXTERNAL_STORE_SECRET="$(rand)"
MINIO_ROOT_USER="c2kminio"
MINIO_ROOT_PASSWORD="$(rand24)"
SMTP_PASS="$(rand24)"
S3_BUCKET="c2k-uploads"

MAIL_USER="noreply@${DOMAIN}"
ADMIN_MAILBOX="admin@${DOMAIN}"

cat >"$ENV_FILE" <<EOF
NODE_ENV=production
USE_DATABASE=true
DATABASE_URL=postgresql://c2k:${POSTGRES_PASSWORD}@postgres:5432/c2k
REDIS_URL=redis://redis:6379

AUTH_SECRET=${AUTH_SECRET}
COOKIE_SECRET=${COOKIE_SECRET}
AUTH_ALLOW_FALLBACK=false

CORS_ORIGIN=https://${DOMAIN}
C2K_PUBLIC_WEB_URL=https://${DOMAIN}
API_PUBLIC_URL=https://${DOMAIN}
DOMAIN=${DOMAIN}
VITE_SITE_URL=https://${DOMAIN}

POSTGRES_USER=c2k
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=c2k

MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
S3_ENDPOINT=http://minio:9000
S3_BUCKET=${S3_BUCKET}
S3_REGION=us-east-1
S3_ACCESS_KEY=${MINIO_ROOT_USER}
S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
S3_PUBLIC_BASE_URL=https://${DOMAIN}/c2k-uploads

CLAMD_HOST=clamav
CLAMD_PORT=3310

C2K_MAIL_TRANSPORT=smtp
C2K_MAIL_FROM="Kink.Social <${MAIL_USER}>"
C2K_MAIL_REPLY_TO=support@${DOMAIN}
SMTP_HOST=mailserver
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=${MAIL_USER}
SMTP_PASS=${SMTP_PASS}

C2K_PASSWORD_RESET_ENABLED=true
C2K_PLATFORM_MAIL_BCC=${ADMIN_MAILBOX}
C2K_PLATFORM_ADMIN_EMAILS=${ADMIN_MAILBOX}
C2K_ORG_JOIN_EMAIL=true
C2K_EVENT_RSVP_EMAIL=true
C2K_ACCOUNT_WELCOME_EMAIL=true
C2K_SCOPE_EMAIL_DOUBLE_OPTIN=true

C2K_FIELD_ENCRYPTION_KEY=${FIELD_KEY}
EMAIL_LOOKUP_PEPPER=${EMAIL_PEPPER}
EXTERNAL_STORE_SECRET=${EXTERNAL_STORE_SECRET}

BRAX_ADMIN_EMAIL=brax@${DOMAIN}
BRAX_ADMIN_PASSWORD=${BRAX_ADMIN_PASSWORD:-ChangeMeAfterLogin!}

# Persist SMTP creds for mailserver setup script
C2K_SMTP_MAILBOX=${MAIL_USER}
C2K_SMTP_MAILBOX_PASSWORD=${SMTP_PASS}
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"
echo "SMTP mailbox: ${MAIL_USER}"
echo "Admin email: ${ADMIN_EMAIL}"
