/** Fixtures for ISO share card model + PNG review. */

export const BRAX_ISO_STRUCTURED = {
  version: 'iso_v2' as const,
  into: [
    'fire',
    'wax',
    'breath',
    'knife',
    'thuddy',
    'impact',
    'rough_body',
    'primal',
    'cgl',
    'degradation',
    'hypno',
    'forced_orgasm',
    'massage',
    'groping',
    'sex',
    'oral',
    'makeouts',
    'hucow',
    'roleplay',
    'stingy',
    'sensory_dep',
    'freeuse',
    'cnc',
    'orgasm_control',
    'praise',
    'mindfuck',
  ],
  roles: ['switch', 'primal'],
  venues: ['dungeon', 'outdoor', 'private'],
  curious: ['cnc'],
  hardNos: ['stingy', 'needles'],
  pitches: [
    {
      id: '48ae4aab-52bd-4a12-a85c-4367a8388f09',
      sex: 'optional' as const,
      tags: ['knife', 'primal', 'cgl', 'rough_body', 'fire', 'thuddy', 'impact'],
      title: 'Seeking to top or bottom for anything I have listed',
      myRole: 'either' as const,
      intensity: 'planned' as const,
      description: 'Looking for fun casual energy for a first time session.',
    },
  ],
  approach: 'dms_open' as const,
  capacity: 'selective' as const,
  riskNotes: 'Generally need to debrief after a scene',
  playIntent: 'open' as const,
  seekingWho: [
    'women',
    'anyone',
    'nonbinary',
    'trans_fem',
    'bi_curious_partners',
    'open_exploring',
    'friends_first',
  ],
  gearBringing: 'I have my own playkit, but I am happy to use some toys from yours as well!',
  socialOffers: ['lunch', 'swim', 'craft', 'fire', 'sunscreen', 'friends_only'],
  visualSignal: '',
  discordHandle: '',
}

export const MANY_PITCHES_STRUCTURED = {
  ...BRAX_ISO_STRUCTURED,
  pitches: [
    BRAX_ISO_STRUCTURED.pitches[0]!,
    {
      id: 'p2',
      sex: 'none' as const,
      tags: ['rope'],
      title: 'Slow rope & negotiation practice',
      myRole: 'top' as const,
      intensity: 'quick' as const,
      description: 'Thirty minutes, light ties, lots of check-ins.',
    },
    {
      id: 'p3',
      sex: 'optional' as const,
      tags: ['impact'],
      title: 'Thuddy impact warmup',
      myRole: 'bottom' as const,
      intensity: 'planned' as const,
      description: 'Build intensity together.',
    },
    {
      id: 'p4',
      sex: 'yes' as const,
      tags: ['wax'],
      title: 'Wax & sensory play',
      myRole: 'either' as const,
      intensity: 'oddball' as const,
      description: '',
    },
  ],
}
