/** Canonical kink/BDSM interest tags. Seeded into kink_tags and used for Profile Studio browse groups. */
export type KinkTagCatalogEntry = {
  slug: string
  displayName: string
  sortOrder: number
}

export const KINK_TAG_CATALOG: readonly KinkTagCatalogEntry[] = [
  // Rope & bondage (10–19)
  { slug: 'rope-bondage', displayName: 'Rope / bondage', sortOrder: 10 },
  { slug: 'shibari', displayName: 'Shibari / kinbaku', sortOrder: 11 },
  { slug: 'western-bondage', displayName: 'Western bondage', sortOrder: 12 },
  { slug: 'suspension', displayName: 'Suspension', sortOrder: 13 },
  { slug: 'floor-work', displayName: 'Floor work / partial ties', sortOrder: 14 },
  { slug: 'cuffs-restraints', displayName: 'Cuffs & restraints', sortOrder: 15 },
  { slug: 'mummification', displayName: 'Mummification / wrapping', sortOrder: 16 },
  { slug: 'predicament-bondage', displayName: 'Predicament bondage', sortOrder: 17 },
  { slug: 'self-bondage', displayName: 'Self-bondage', sortOrder: 18 },
  { slug: 'chest-harness', displayName: 'Chest harness', sortOrder: 19 },
  { slug: 'hogtie', displayName: 'Hogtie', sortOrder: 19 },
  { slug: 'strappado', displayName: 'Strappado', sortOrder: 19 },
  { slug: 'column-tie', displayName: 'Column tie', sortOrder: 19 },
  { slug: 'box-tie', displayName: 'Box tie / takate kote', sortOrder: 19 },
  { slug: 'futomomo', displayName: 'Futomomo / leg ties', sortOrder: 19 },
  { slug: 'chain-bondage', displayName: 'Chain bondage', sortOrder: 19 },
  { slug: 'metal-bondage', displayName: 'Metal bondage', sortOrder: 19 },
  { slug: 'spreader-bar', displayName: 'Spreader bar', sortOrder: 19 },
  { slug: 'armbinders', displayName: 'Armbinders', sortOrder: 19 },
  { slug: 'straitjacket', displayName: 'Straitjacket', sortOrder: 19 },
  { slug: 'stocks-pillory', displayName: 'Stocks / pillory', sortOrder: 19 },
  { slug: 'vacuum-bed', displayName: 'Vacuum bed / inflatable', sortOrder: 19 },
  { slug: 'bondage-tape', displayName: 'Bondage tape / wrap', sortOrder: 19 },

  // Impact (20–29)
  { slug: 'impact-play', displayName: 'Impact play', sortOrder: 20 },
  { slug: 'spanking', displayName: 'Spanking', sortOrder: 21 },
  { slug: 'flogging', displayName: 'Flogging', sortOrder: 22 },
  { slug: 'paddling', displayName: 'Paddling', sortOrder: 23 },
  { slug: 'caning', displayName: 'Caning', sortOrder: 24 },
  { slug: 'crop-single-tail', displayName: 'Crop / single-tail', sortOrder: 25 },
  { slug: 'slapping', displayName: 'Slapping (face/body)', sortOrder: 26 },
  { slug: 'bastinado', displayName: 'Bastinado / foot impact', sortOrder: 27 },
  { slug: 'tawse', displayName: 'Tawse', sortOrder: 28 },
  { slug: 'sjambok', displayName: 'Sjambok / heavy leather', sortOrder: 28 },
  { slug: 'martinet', displayName: 'Martinet', sortOrder: 28 },
  { slug: 'belt-play', displayName: 'Belt play', sortOrder: 28 },
  { slug: 'punch-play', displayName: 'Punch play / rough body', sortOrder: 28 },
  { slug: 'hair-pulling', displayName: 'Hair pulling', sortOrder: 28 },
  { slug: 'biting', displayName: 'Biting', sortOrder: 28 },
  { slug: 'switch-play', displayName: 'Switch play', sortOrder: 29 },

  // Sensation (30–39)
  { slug: 'sensation-play', displayName: 'Sensation play', sortOrder: 30 },
  { slug: 'wax-play', displayName: 'Wax play', sortOrder: 31 },
  { slug: 'ice-play', displayName: 'Ice / temperature', sortOrder: 32 },
  { slug: 'electro-play', displayName: 'Electro / e-stim', sortOrder: 33 },
  { slug: 'needle-play', displayName: 'Needle / piercing play', sortOrder: 34 },
  { slug: 'knife-play', displayName: 'Knife / edge play', sortOrder: 35 },
  { slug: 'tickling', displayName: 'Tickling', sortOrder: 36 },
  { slug: 'breath-play', displayName: 'Breath play (advanced)', sortOrder: 37 },
  { slug: 'sensory-deprivation', displayName: 'Sensory deprivation', sortOrder: 38 },
  { slug: 'fire-play', displayName: 'Fire play (advanced)', sortOrder: 39 },
  { slug: 'cupping', displayName: 'Cupping', sortOrder: 39 },
  { slug: 'wartenberg-wheel', displayName: 'Wartenberg wheel / pinwheel', sortOrder: 39 },
  { slug: 'figging', displayName: 'Figging', sortOrder: 39 },
  { slug: 'scratch-play', displayName: 'Scratching / nails', sortOrder: 39 },
  { slug: 'clothespins', displayName: 'Clothespins / clamps (sensation)', sortOrder: 39 },
  { slug: 'nipple-play', displayName: 'Nipple play / torture', sortOrder: 39 },
  { slug: 'genital-sensation', displayName: 'Genital sensation play', sortOrder: 39 },
  { slug: 'violet-wand', displayName: 'Violet wand', sortOrder: 39 },
  { slug: 'branding-temporary', displayName: 'Temporary branding', sortOrder: 39 },

  // Power exchange & dynamics (40–49)
  { slug: 'protocol', displayName: 'Protocol / structure', sortOrder: 40 },
  { slug: 'service', displayName: 'Service', sortOrder: 41 },
  { slug: 'dom-sub', displayName: 'D/s dynamics', sortOrder: 42 },
  { slug: 'master-slave', displayName: 'M/s dynamics', sortOrder: 43 },
  { slug: 'ownership', displayName: 'Ownership / collaring', sortOrder: 44 },
  { slug: 'discipline', displayName: 'Discipline / punishment', sortOrder: 45 },
  { slug: 'rules-rituals', displayName: 'Rules & rituals', sortOrder: 46 },
  { slug: 'tpe', displayName: 'Total power exchange', sortOrder: 47 },
  { slug: 'caregiver-little', displayName: 'Caregiver / little', sortOrder: 48 },
  { slug: 'pet-play', displayName: 'Pet play', sortOrder: 49 },
  { slug: 'obedience-training', displayName: 'Obedience training', sortOrder: 49 },
  { slug: 'domestic-service', displayName: 'Domestic service', sortOrder: 49 },
  { slug: 'sexual-service', displayName: 'Sexual service', sortOrder: 49 },
  { slug: '24-7-dynamics', displayName: '24/7 dynamics', sortOrder: 49 },
  { slug: 'weekend-dynamics', displayName: 'Weekend / part-time dynamics', sortOrder: 49 },
  { slug: 'scene-only-dynamics', displayName: 'Scene-only dynamics', sortOrder: 49 },
  { slug: 'high-protocol', displayName: 'High protocol', sortOrder: 49 },
  { slug: 'low-protocol', displayName: 'Low protocol', sortOrder: 49 },
  { slug: 'bratting', displayName: 'Bratting', sortOrder: 49 },
  { slug: 'brat-taming', displayName: 'Brat taming', sortOrder: 49 },
  { slug: 'gentle-domination', displayName: 'Gentle domination', sortOrder: 49 },
  { slug: 'daddy-dom', displayName: 'Daddy / Mommy dom', sortOrder: 49 },
  { slug: 'slave-training', displayName: 'Slave training', sortOrder: 49 },
  { slug: 'keyholding', displayName: 'Keyholding', sortOrder: 49 },

  // Roleplay & personas (50–59)
  { slug: 'roleplay', displayName: 'Roleplay', sortOrder: 50 },
  { slug: 'primal', displayName: 'Primal play', sortOrder: 51 },
  { slug: 'humiliation', displayName: 'Humiliation / degradation', sortOrder: 52 },
  { slug: 'objectification', displayName: 'Objectification', sortOrder: 53 },
  { slug: 'uniforms-costumes', displayName: 'Uniforms / costumes', sortOrder: 54 },
  { slug: 'medical-play', displayName: 'Medical play', sortOrder: 55 },
  { slug: 'age-play', displayName: 'Age play (adult)', sortOrder: 56 },
  { slug: 'fantasy-scenarios', displayName: 'Fantasy scenarios', sortOrder: 57 },
  { slug: 'cnc', displayName: 'Consensual non-consent (CNC)', sortOrder: 58 },
  { slug: 'kidnapping-roleplay', displayName: 'Kidnapping / capture roleplay', sortOrder: 58 },
  { slug: 'interrogation-roleplay', displayName: 'Interrogation roleplay', sortOrder: 58 },
  { slug: 'prisoner-guard', displayName: 'Prisoner / guard', sortOrder: 58 },
  { slug: 'boss-employee', displayName: 'Boss / employee', sortOrder: 58 },
  { slug: 'teacher-student', displayName: 'Teacher / student (adult)', sortOrder: 58 },
  { slug: 'cop-robber', displayName: 'Cop / robber', sortOrder: 58 },
  { slug: 'monster-fantasy', displayName: 'Monster / creature fantasy', sortOrder: 58 },
  { slug: 'breeding-kink', displayName: 'Breeding kink', sortOrder: 58 },
  { slug: 'free-use', displayName: 'Free use (negotiated)', sortOrder: 58 },
  { slug: 'puppy-play', displayName: 'Puppy play', sortOrder: 59 },
  { slug: 'kitten-play', displayName: 'Kitten play', sortOrder: 59 },
  { slug: 'pony-play', displayName: 'Pony play', sortOrder: 59 },
  { slug: 'handler-play', displayName: 'Handler / trainer', sortOrder: 59 },
  { slug: 'maid-service-roleplay', displayName: 'Maid / butler service', sortOrder: 59 },

  // Fetish & materials (60–69)
  { slug: 'leather', displayName: 'Leather', sortOrder: 60 },
  { slug: 'latex-rubber', displayName: 'Latex / rubber', sortOrder: 61 },
  { slug: 'boot-worship', displayName: 'Boot / shoe worship', sortOrder: 62 },
  { slug: 'foot-fetish', displayName: 'Foot fetish', sortOrder: 63 },
  { slug: 'lingerie', displayName: 'Lingerie / fetish wear', sortOrder: 64 },
  { slug: 'cross-dressing', displayName: 'Cross-dressing / gender play', sortOrder: 65 },
  { slug: 'body-worship', displayName: 'Body worship', sortOrder: 66 },
  { slug: 'chastity', displayName: 'Chastity / orgasm control', sortOrder: 67 },
  { slug: 'feminization', displayName: 'Feminization / sissification', sortOrder: 68 },
  { slug: 'masculinization', displayName: 'Masculinization play', sortOrder: 69 },
  { slug: 'corsets', displayName: 'Corsets / tightlacing', sortOrder: 69 },
  { slug: 'gas-masks-hoods', displayName: 'Gas masks / hoods', sortOrder: 69 },
  { slug: 'blindfolds', displayName: 'Blindfolds', sortOrder: 69 },
  { slug: 'gags', displayName: 'Gags', sortOrder: 69 },
  { slug: 'high-heels', displayName: 'High heels', sortOrder: 69 },
  { slug: 'stockings-pantyhose', displayName: 'Stockings / pantyhose', sortOrder: 69 },
  { slug: 'pvc-vinyl', displayName: 'PVC / vinyl', sortOrder: 69 },
  { slug: 'fur-fetish', displayName: 'Fur fetish', sortOrder: 69 },
  { slug: 'food-play', displayName: 'Food play', sortOrder: 69 },
  { slug: 'sploshing', displayName: 'Sploshing / messy play', sortOrder: 69 },
  { slug: 'spit-play', displayName: 'Spit play', sortOrder: 69 },
  { slug: 'watersports', displayName: 'Watersports', sortOrder: 69 },
  { slug: 'face-sitting', displayName: 'Face sitting / queening', sortOrder: 69 },
  { slug: 'smothering', displayName: 'Smothering (negotiated)', sortOrder: 69 },
  { slug: 'trampling', displayName: 'Trampling', sortOrder: 69 },
  { slug: 'musk-sweat', displayName: 'Musk / sweat', sortOrder: 69 },
  { slug: 'hair-fetish', displayName: 'Hair fetish', sortOrder: 69 },
  { slug: 'collars-symbolic', displayName: 'Collars (symbolic / fashion)', sortOrder: 69 },

  // Group & social (70–79)
  { slug: 'group-play', displayName: 'Group scenes', sortOrder: 70 },
  { slug: 'threesomes', displayName: 'Threesomes', sortOrder: 71 },
  { slug: 'orgies', displayName: 'Orgies / parties', sortOrder: 72 },
  { slug: 'voyeurism', displayName: 'Voyeurism', sortOrder: 73 },
  { slug: 'exhibitionism', displayName: 'Exhibitionism', sortOrder: 74 },
  { slug: 'cuckolding', displayName: 'Cuckolding / hotwife', sortOrder: 75 },
  { slug: 'swinging', displayName: 'Swinging', sortOrder: 76 },
  { slug: 'munches', displayName: 'Munches / social', sortOrder: 77 },
  { slug: 'gangbang', displayName: 'Gangbang (negotiated)', sortOrder: 78 },
  { slug: 'double-penetration', displayName: 'Double penetration', sortOrder: 78 },
  { slug: 'parallel-play', displayName: 'Parallel play', sortOrder: 78 },
  { slug: 'soft-swap', displayName: 'Soft swap', sortOrder: 78 },
  { slug: 'full-swap', displayName: 'Full swap', sortOrder: 78 },
  { slug: 'play-parties', displayName: 'Play parties', sortOrder: 78 },
  { slug: 'dungeon-play', displayName: 'Dungeon play', sortOrder: 78 },
  { slug: 'public-play', displayName: 'Public play (consensual)', sortOrder: 79 },

  // Body & intimacy (80–89)
  { slug: 'massage', displayName: 'Massage', sortOrder: 80 },
  { slug: 'hypnosis', displayName: 'Hypnosis / trance', sortOrder: 81 },
  { slug: 'orgasm-control', displayName: 'Orgasm control / edging', sortOrder: 82 },
  { slug: 'tease-denial', displayName: 'Tease & denial', sortOrder: 83 },
  { slug: 'sensual-play', displayName: 'Sensual / vanilla-adjacent', sortOrder: 84 },
  { slug: 'oral-fixation', displayName: 'Oral fixation', sortOrder: 85 },
  { slug: 'anal-play', displayName: 'Anal play', sortOrder: 86 },
  { slug: 'pegging', displayName: 'Pegging', sortOrder: 87 },
  { slug: 'fisting', displayName: 'Fisting (advanced)', sortOrder: 88 },
  { slug: 'deep-throat', displayName: 'Deep throat / throat play', sortOrder: 89 },
  { slug: 'face-fucking', displayName: 'Face fucking (negotiated)', sortOrder: 89 },
  { slug: 'prostate-play', displayName: 'Prostate play', sortOrder: 89 },
  { slug: 'breast-play', displayName: 'Breast play', sortOrder: 89 },
  { slug: 'hickies', displayName: 'Hickies / marking', sortOrder: 89 },
  { slug: 'mutual-masturbation', displayName: 'Mutual masturbation', sortOrder: 89 },
  { slug: 'toys-vibrators', displayName: 'Toys / vibrators', sortOrder: 89 },
  { slug: 'dildos', displayName: 'Dildos / insertables', sortOrder: 89 },
  { slug: 'butt-plugs', displayName: 'Butt plugs', sortOrder: 89 },
  { slug: 'rimming', displayName: 'Rimming', sortOrder: 89 },
  { slug: 'forced-orgasm', displayName: 'Forced orgasm (negotiated)', sortOrder: 89 },

  // Care & aftercare (90–99)
  { slug: 'aftercare', displayName: 'Aftercare focus', sortOrder: 90 },
  { slug: 'cuddling', displayName: 'Cuddling / intimacy', sortOrder: 91 },
  { slug: 'tantra', displayName: 'Tantra / mindful touch', sortOrder: 92 },
  { slug: 'sub-drop-awareness', displayName: 'Sub drop / dom drop awareness', sortOrder: 93 },
  { slug: 'safewords', displayName: 'Safewords / traffic lights', sortOrder: 94 },
  { slug: 'scene-debrief', displayName: 'Scene debrief / check-ins', sortOrder: 95 },

  // Community & creative (100–109)
  { slug: 'education', displayName: 'Education / workshops', sortOrder: 100 },
  { slug: 'mentorship', displayName: 'Mentorship', sortOrder: 101 },
  { slug: 'photography', displayName: 'Photography (artistic)', sortOrder: 102 },
  { slug: 'writing', displayName: 'Writing / discussion', sortOrder: 103 },
  { slug: 'performance', displayName: 'Performance / demo bottom', sortOrder: 104 },
  { slug: 'volunteering', displayName: 'Volunteering / dungeon staff', sortOrder: 105 },
  { slug: 'event-organizing', displayName: 'Event organizing', sortOrder: 106 },
  { slug: 'poly-enm', displayName: 'Poly / ENM', sortOrder: 107 },
  { slug: 'negotiation', displayName: 'Scene negotiation', sortOrder: 108 },
  { slug: 'consent-culture', displayName: 'Consent culture', sortOrder: 109 },
  { slug: 'rope-classes', displayName: 'Rope classes', sortOrder: 109 },
  { slug: 'dungeon-monitor', displayName: 'Dungeon monitor (DM)', sortOrder: 109 },

  // Restraints & gear (110–119)
  { slug: 'ball-gag', displayName: 'Ball gag', sortOrder: 110 },
  { slug: 'ring-gag', displayName: 'Ring gag', sortOrder: 111 },
  { slug: 'bit-gag', displayName: 'Bit gag', sortOrder: 112 },
  { slug: 'muzzle-play', displayName: 'Muzzle play', sortOrder: 113 },
  { slug: 'posture-collar', displayName: 'Posture collar', sortOrder: 114 },
  { slug: 'bondage-furniture', displayName: 'Bondage furniture / crosses', sortOrder: 115 },
  { slug: 'suspension-rigging', displayName: 'Suspension rigging (advanced)', sortOrder: 116 },
  { slug: 'rope-care', displayName: 'Rope care / conditioning', sortOrder: 117 },

  // Edge & advanced (120–129)
  { slug: 'blood-play', displayName: 'Blood play (advanced)', sortOrder: 120 },
  { slug: 'suspension-bondage', displayName: 'Suspension bondage (advanced)', sortOrder: 121 },
  { slug: 'urethral-play', displayName: 'Urethral play (advanced)', sortOrder: 122 },
  { slug: 'sound-play', displayName: 'Sound play (advanced)', sortOrder: 123 },
  { slug: 'cbt', displayName: 'CBT (advanced)', sortOrder: 124 },
  { slug: 'heavy-bondage', displayName: 'Heavy bondage / strict', sortOrder: 125 },
  { slug: 'fear-play', displayName: 'Fear play (negotiated)', sortOrder: 126 },

  // D/s & identity styles (130–139)
  { slug: 'femdom', displayName: 'Femdom', sortOrder: 130 },
  { slug: 'maledom', displayName: 'Maledom', sortOrder: 131 },
  { slug: 'service-top', displayName: 'Service top', sortOrder: 132 },
  { slug: 'power-bottom', displayName: 'Power bottom', sortOrder: 133 },
  { slug: 'switch-dynamics', displayName: 'Switch dynamics', sortOrder: 134 },
  { slug: 'queer-kink', displayName: 'Queer kink', sortOrder: 135 },
  { slug: 'gay-kink', displayName: 'Gay kink', sortOrder: 136 },
  { slug: 'lesbian-kink', displayName: 'Lesbian kink', sortOrder: 137 },
  { slug: 'bi-pan-kink', displayName: 'Bi / pan kink', sortOrder: 138 },
  { slug: 'body-positive-kink', displayName: 'Body-positive kink', sortOrder: 139 },
  { slug: 'disabled-kink', displayName: 'Disabled kink / adaptive play', sortOrder: 139 },
  { slug: 'newbie-friendly', displayName: 'Newbie-friendly', sortOrder: 139 },
  { slug: 'veteran-scene', displayName: 'Veteran / experienced', sortOrder: 139 },
] as const

/** Browse chips in Profile Studio. sortOrder ranges map to the catalog sections above. */
export const KINK_TAG_BROWSE_GROUPS: readonly { label: string; sortOrderMin: number; sortOrderMax: number }[] = [
  { label: 'Rope & bondage', sortOrderMin: 10, sortOrderMax: 19 },
  { label: 'Impact', sortOrderMin: 20, sortOrderMax: 29 },
  { label: 'Sensation', sortOrderMin: 30, sortOrderMax: 39 },
  { label: 'Power exchange', sortOrderMin: 40, sortOrderMax: 49 },
  { label: 'Roleplay', sortOrderMin: 50, sortOrderMax: 59 },
  { label: 'Fetish & materials', sortOrderMin: 60, sortOrderMax: 69 },
  { label: 'Group & social', sortOrderMin: 70, sortOrderMax: 79 },
  { label: 'Body & intimacy', sortOrderMin: 80, sortOrderMax: 89 },
  { label: 'Aftercare', sortOrderMin: 90, sortOrderMax: 99 },
  { label: 'Community', sortOrderMin: 100, sortOrderMax: 109 },
  { label: 'Gear', sortOrderMin: 110, sortOrderMax: 119 },
  { label: 'Advanced', sortOrderMin: 120, sortOrderMax: 129 },
  { label: 'Styles & identity', sortOrderMin: 130, sortOrderMax: 139 },
]

const slugSortOrder = new Map(KINK_TAG_CATALOG.map((t) => [t.slug, t.sortOrder]))

export function kinkTagSortOrderForSlug(slug: string): number | undefined {
  return slugSortOrder.get(slug)
}

export function kinkTagCatalogSlugsInRange(min: number, max: number): readonly string[] {
  return KINK_TAG_CATALOG.filter((t) => t.sortOrder >= min && t.sortOrder <= max).map((t) => t.slug)
}
