/**
 * Pickup-play negotiation catalog — inspired by common BDSM negotiation
 * starter checklists (activities, roles, sensation, marks, aftercare).
 * Original labels for kink.social; not a copy of any single published form.
 */

export type CatalogCategoryId =
  | 'bondage'
  | 'impact'
  | 'sensation'
  | 'power'
  | 'roles'
  | 'body'
  | 'intimacy'
  | 'edge'
  | 'social'
  | 'fetish'

export type CatalogItem = {
  id: string
  label: string
  category: CatalogCategoryId
}

export const CATALOG_CATEGORIES: { id: CatalogCategoryId; label: string; blurb: string }[] = [
  { id: 'bondage', label: 'Bondage', blurb: 'Rope, cuffs, gags, furniture, wrap…' },
  { id: 'impact', label: 'Impact', blurb: 'Hands through whips — light, thuddy, stingy, heavy' },
  { id: 'sensation', label: 'Sensation', blurb: 'Temp, electro, tickle, knives, clamps, mindfuck…' },
  { id: 'power', label: 'Power', blurb: 'Service, orders, objectification, denial…' },
  { id: 'roles', label: 'Roles', blurb: 'Pet, predator/prey, ritual, primal…' },
  { id: 'body', label: 'Body', blurb: 'Where play lands; mark comfort' },
  { id: 'intimacy', label: 'Intimacy', blurb: 'Touch, sex & fluids — only if on the table' },
  { id: 'fetish', label: 'Fetish', blurb: 'Leather, latex, boots, gear energy…' },
  { id: 'edge', label: 'Edge / taboo', blurb: 'Discuss thoroughly; venue rules apply' },
  { id: 'social', label: 'Social', blurb: 'Demo, teaching, audience, photos, group…' },
]

function items(category: CatalogCategoryId, pairs: [string, string][]): CatalogItem[] {
  return pairs.map(([id, label]) => ({ id, label, category }))
}

/**
 * Large activity catalog for seeking / offering / maybe / hard-nos.
 * Seeking ≈ receive / bottom energy; Offering ≈ give / top energy.
 * Edge & taboo items are listed so people can hard-no them — venue rules still win.
 */
export const PICKUP_PLAY_CATALOG: CatalogItem[] = [
  ...items('bondage', [
    ['blindfolds', 'Blindfolds'],
    ['collar_lead', 'Collar / lead'],
    ['leather_cuffs', 'Leather cuffs'],
    ['metal_cuffs', 'Metal cuffs / handcuffs'],
    ['soft_restraints', 'Soft / fabric restraints'],
    ['chain_restraints', 'Chain restraints'],
    ['thumb_cuffs', 'Thumb cuffs'],
    ['gags', 'Gags (ball, bit, tape…)'],
    ['bit_gag', 'Bit gag'],
    ['ring_gag', 'Ring / O-ring gag'],
    ['panel_gag', 'Panel / muzzle gag'],
    ['spider_gag', 'Spider gag'],
    ['rope_floor', 'Rope — floor / decorative'],
    ['rope_restrictive', 'Rope — restrictive'],
    ['rope_tk', 'Rope — box tie / TK'],
    ['rope_hips', 'Rope — hips / harness'],
    ['rope_legs', 'Rope — leg / futomomo'],
    ['rope_crotch', 'Rope — crotch rope / karada'],
    ['rope_breast', 'Rope — breast bondage'],
    ['shibari_aesthetic', 'Shibari / aesthetic rope'],
    ['hogtie', 'Hogtie'],
    ['frogtie', 'Frogtie'],
    ['predicament_bondage', 'Predicament bondage'],
    ['spreader_bar', 'Spreader bar'],
    ['armbinders', 'Armbinders / monoglove'],
    ['straitjacket', 'Straitjacket'],
    ['suspension', 'Suspension (if venue allows)'],
    ['partial_suspension', 'Partial suspension'],
    ['inverted_suspension', 'Inverted suspension (skill gated)'],
    ['furniture_bondage', 'Cross / bench / table bondage'],
    ['stocks_pillory', 'Stocks / pillory (if available)'],
    ['cages', 'Cage time'],
    ['hoods', 'Hoods'],
    ['gas_mask', 'Gas mask / rebreather vibe'],
    ['mummification', 'Mummification / wrap'],
    ['vacuum_bed', 'Vacuum bed (if available)'],
    ['tape_bondage', 'Tape bondage'],
    ['plastic_wrap', 'Plastic wrap / cling film'],
    ['sleepsack', 'Sleepsack / body bag'],
    ['mental_bondage', 'Mental bondage / “stay”'],
    ['chastity_device', 'Chastity device (negotiated)'],
    ['genital_bondage', 'Genital bondage / cock & ball ties'],
    ['long_term_bondage', 'Longer restraint block'],
    ['stress_positions', 'Stress positions (negotiated)'],
    ['foreplay_tying', 'Tying as foreplay / slow bind'],
  ]),
  ...items('impact', [
    ['spanking_hand', 'Hand spanking'],
    ['slapping_body', 'Body slapping (non-face)'],
    ['otk_spanking', 'Over-the-knee spanking'],
    ['paddles', 'Paddles'],
    ['hairbrush', 'Hairbrush / small paddle'],
    ['floggers', 'Floggers'],
    ['heavy_floggers', 'Heavy floggers'],
    ['suede_flogger', 'Suede / soft flogger'],
    ['canes', 'Canes'],
    ['rattan_cane', 'Rattan cane'],
    ['delrin_cane', 'Synthetic / Delrin cane'],
    ['crops', 'Crops'],
    ['straps', 'Straps / belts'],
    ['slapper', 'Slapper / tawse'],
    ['whips', 'Single-tail / whips'],
    ['dragon_tail', 'Dragon’s tail'],
    ['quirt', 'Quirt'],
    ['batons', 'Batons / sticks'],
    ['birch', 'Birch / switch'],
    ['punching', 'Punching / body blows'],
    ['kicking', 'Kicking (controlled)'],
    ['kneeing', 'Kneeing / thigh strikes'],
    ['bastinado', 'Bastinado / sole impact'],
    ['belly_punch', 'Belly punches (negotiated)'],
    ['breast_spanking', 'Breast spanking'],
    ['cock_ball_impact', 'Cock / ball impact'],
    ['impact_light', 'Impact — light / warm-up'],
    ['impact_medium', 'Impact — medium'],
    ['impact_heavy', 'Impact — heavy'],
    ['impact_stingy', 'Stingy impact'],
    ['impact_thuddy', 'Thuddy impact'],
    ['impact_endurance', 'Impact endurance / longer set'],
    ['impact_marks_goal', 'Impact with marks as a goal'],
    ['belting', 'Belting'],
  ]),
  ...items('sensation', [
    ['biting', 'Biting'],
    ['scratching', 'Scratching / nails'],
    ['hair_pull', 'Hair pulling'],
    ['nipples', 'Nipple play'],
    ['nipple_clamps', 'Nipple clamps'],
    ['nipple_weights', 'Nipple weights'],
    ['tickling', 'Tickling'],
    ['feathers', 'Feathers / light tease'],
    ['fur_sensation', 'Fur / soft texture'],
    ['ice_fire', 'Temperature (ice / heat)'],
    ['wax', 'Wax play'],
    ['hot_cold_contrast', 'Hot/cold contrast'],
    ['electro', 'Electricity / TENS'],
    ['violet_wand', 'Violet wand'],
    ['e_stim_boxes', 'E-stim boxes / pads'],
    ['pinwheels', 'Wartenberg / pinwheels'],
    ['knives_edge', 'Knife / edge sensation (dull or discussed)'],
    ['pressure_points', 'Pressure points'],
    ['sensory_dep', 'Sensory deprivation'],
    ['earplugs_headphones', 'Earplugs / noise isolation'],
    ['overstim', 'Overstimulation'],
    ['mindfuck', 'Mindfuck / psychological'],
    ['clothespins', 'Clothespins / clamps'],
    ['zipper_clamps', 'Zipper (clamp run)'],
    ['cupping', 'Cupping'],
    ['suction', 'Suction / pumps'],
    ['breast_pump', 'Breast / chest pumping'],
    ['vacuum_pump_genitals', 'Genital pumping'],
    ['fire_play', 'Fire play (if venue allows)'],
    ['figging', 'Figging (negotiated)'],
    ['medical_sensation', 'Medical-play sensation (exam vibe)'],
    ['cbt_sensation', 'Genital sensation / CBT-lite'],
    ['ballbusting', 'Ballbusting (negotiated)'],
    ['cock_tease', 'Cock teasing / denial touch'],
    ['perineum_pressure', 'Perineum / prostate external pressure'],
    ['abrasion', 'Abrasion / rough texture'],
    ['stingy_clips', 'Stingy clips / clamps endurance'],
    ['sensation_contrast', 'Sensation contrast play'],
    ['blind_tease', 'Blindfolded tease'],
  ]),
  ...items('power', [
    ['orders', 'Orders / being ordered'],
    ['protocol_light', 'Light protocol / manners'],
    ['protocol_formal', 'Formal protocol / positions'],
    ['titles_honorifics', 'Titles / honorifics'],
    ['kneeling_present', 'Kneeling / presentation'],
    ['service', 'Service (practical or erotic)'],
    ['bootblack', 'Bootblacking / gear care'],
    ['domestic_service', 'Domestic service (scene-scoped)'],
    ['objectification', 'Objectification'],
    ['human_furniture', 'Human furniture'],
    ['human_ashtray', 'Human ashtray (venue & consent)'],
    ['degradation_verbal', 'Verbal degradation / humiliation'],
    ['humiliation_public', 'Public humiliation (venue-safe)'],
    ['body_shaming_play', 'Body-shame play (consensual only)'],
    ['name_calling', 'Name-calling (negotiated words)'],
    ['praise', 'Praise / affirmation kink'],
    ['orgasm_control', 'Orgasm control / denial'],
    ['orgasm_torture', 'Orgasm torture / forced orgasm'],
    ['chastity_keyholding', 'Chastity / keyholding energy'],
    ['inspection', 'Inspection'],
    ['forced_pose', 'Forced posing / presentation'],
    ['forced_nudity', 'Forced nudity (venue-safe)'],
    ['forced_clothing', 'Forced clothing / dress-up'],
    ['corner_time', 'Corner time / timeout'],
    ['writing_lines', 'Writing lines / tasks'],
    ['begging', 'Begging / pleading'],
    ['permission_culture', 'Permission for small things'],
    ['ownership_talk', 'Ownership language (scene-only)'],
    ['collar_ceremony', 'Collaring energy (scene-scoped)'],
    ['ignore_neglect', 'Consensual ignore / neglect play'],
    ['silent_treatment', 'Silent treatment (consensual)'],
    ['mind_control_hypno', 'Hypnosis / mind-control flavor (negotiated)'],
    ['blackmail_fantasy', 'Blackmail fantasy (fully negotiated fiction)'],
    ['financial_flavor', 'Findom flavor (scene talk only — no real transfers)'],
    ['spit_play', 'Spit play'],
    ['face_slapping_power', 'Face slapping as dominance'],
    ['worship_receiving', 'Receiving worship'],
    ['worship_giving', 'Giving worship'],
    ['training_tasks', 'Training / conditioning tasks'],
    ['rules_for_scene', 'Scene rules & consequences'],
  ]),
  ...items('roles', [
    ['pet_play', 'Pet play'],
    ['puppy_play', 'Puppy play'],
    ['kitten_play', 'Kitten play'],
    ['pony_play', 'Pony play'],
    ['cow_play', 'Cow / livestock flavor'],
    ['pig_play', 'Pig play'],
    ['pred_prey', 'Predator / prey'],
    ['owner_property', 'Owner / property energy'],
    ['master_slave', 'Master / slave aesthetic (scene-scoped)'],
    ['service_dynamic', 'Service dynamic'],
    ['teacher_student', 'Teacher / student flavor'],
    ['boss_employee', 'Boss / employee flavor'],
    ['captive', 'Captor / captive flavor'],
    ['kidnap_fantasy', 'Kidnap / snatch fantasy (negotiated)'],
    ['interrogation_role', 'Interrogation roleplay'],
    ['military_role', 'Military / drill flavor'],
    ['police_criminal', 'Authority / criminal flavor'],
    ['medical_role', 'Medical / exam roleplay'],
    ['nurse_patient', 'Nurse / patient flavor'],
    ['uniform_role', 'Uniform / authority flavor'],
    ['caregiver_little', 'Caregiver / little energy (adult)'],
    ['daddy_mommy', 'Daddy / Mommy dynamic flavor (adult)'],
    ['brat_tamer', 'Brat / tamer energy'],
    ['ritual', 'Ritual / ceremonial vibe'],
    ['primal', 'Primal'],
    ['wrestling_roles', 'Wrestling / struggle energy'],
    ['goddess_worship', 'Goddess / deity worship vibe'],
    ['god_worship', 'God / deity worship vibe'],
    ['slave_aesthetic', 'Slave aesthetic (scene-scoped)'],
    ['doll_toy', 'Doll / toy energy'],
    ['secretary_boss', 'Secretary / executive flavor'],
    ['maid_butler', 'Maid / butler service flavor'],
    ['alien_abduction', 'Alien / experimental fantasy'],
    ['monster_prey', 'Monster / creature fantasy'],
    ['vampire_energy', 'Vampire / bite energy'],
  ]),
  ...items('body', [
    ['ass_thighs', 'Ass / thighs focus'],
    ['back_shoulders', 'Back / shoulders'],
    ['chest_breast', 'Chest / breast'],
    ['belly', 'Belly / stomach'],
    ['feet_legs', 'Feet / legs'],
    ['soles', 'Soles of feet'],
    ['hands_arms', 'Hands / arms'],
    ['neck_kiss', 'Neck kissing / nuzzling (no choke)'],
    ['scalp', 'Scalp / head'],
    ['ears_neck', 'Ears / nape'],
    ['inner_thighs', 'Inner thighs'],
    ['ass_cheeks', 'Ass cheeks focus'],
    ['face_slapping', 'Face slapping (negotiated)'],
    ['genital_impact', 'Genital impact (negotiated)'],
    ['breast_impact', 'Breast impact'],
    ['pussy_impact', 'Pussy spanking / impact'],
    ['breath_edge', 'Breath play adjacent — discuss only'],
    ['marks_ok_topic', 'Okay talking about marks'],
    ['hickeys', 'Hickeys / love bites'],
    ['scratch_marks', 'Scratch marks welcome'],
    ['bruise_art', 'Bruise placement as art'],
    ['no_face_marks', 'No marks on face / neck'],
    ['no_visible_marks', 'No visible / coverable-only marks'],
    ['hair_pull_scalp', 'Scalp / hair focus'],
    ['armpits', 'Armpits'],
    ['asshole_focus', 'Asshole / rim focus (consent + hygiene)'],
  ]),
  ...items('intimacy', [
    ['cuddling', 'Cuddling / non-sexual touch'],
    ['kissing', 'Kissing'],
    ['making_out', 'Making out'],
    ['dirty_talk', 'Dirty talk'],
    ['groping', 'Groping over/under clothes'],
    ['body_worship', 'Body worship'],
    ['foot_worship', 'Foot worship'],
    ['ass_worship', 'Ass worship'],
    ['genital_touch', 'Hands on genitals'],
    ['mutual_masturbation', 'Mutual masturbation'],
    ['oral_give', 'Oral — giving'],
    ['oral_receive', 'Oral — receiving'],
    ['cunnilingus', 'Cunnilingus'],
    ['fellatio', 'Fellatio'],
    ['rimming', 'Rimming'],
    ['facesitting', 'Facesitting / smother (airway negotiated)'],
    ['queening', 'Queening'],
    ['grinding', 'Grinding / dry humping'],
    ['toys_external', 'External toys / vibrators'],
    ['toys_penetration', 'Toys / penetration'],
    ['dildo_play', 'Dildo play'],
    ['strap_on', 'Strap-on play'],
    ['pegging', 'Pegging'],
    ['anal_play', 'Anal play'],
    ['anal_fisting', 'Anal fisting (skill + negotiation)'],
    ['vaginal_fisting', 'Vaginal fisting (skill + negotiation)'],
    ['fingering', 'Fingering'],
    ['double_penetration_toys', 'Double penetration (toys / negotiated)'],
    ['orgasms', 'Orgasms as a goal'],
    ['edging_sex', 'Edging / ruined orgasm'],
    ['creampie_talk', 'Creampie fantasy / talk'],
    ['cum_play', 'Cum play (on body / negotiated)'],
    ['swallowing', 'Swallowing'],
    ['facials', 'Facials'],
    ['fluid_barriers', 'Barriers (condoms / dams) expected'],
    ['fluid_exchange', 'Fluid exchange (discussed)'],
    ['bareback_negotiated', 'Barrier-free sex (explicit STI talk)'],
    ['exhibition_touch', 'Exhibitionist touch (venue-safe)'],
    ['sex_in_scene', 'Sex as part of the scene'],
    ['rough_sex', 'Rough sex (still negotiated)'],
    ['gentle_sex', 'Gentle / intimate sex'],
    ['breeding_talk', 'Breeding talk / fantasy (consensual)'],
    ['impregnation_fantasy', 'Impregnation fantasy (talk / role)'],
    ['cuckold_hotwife', 'Cuckold / hotwife energy'],
    ['sharing_partner_sex', 'Partner sharing / swapping energy'],
  ]),
  ...items('fetish', [
    ['leather', 'Leather'],
    ['latex_rubber', 'Latex / rubber'],
    ['pvc_vinyl', 'PVC / vinyl'],
    ['spandex', 'Spandex / lycra'],
    ['boots', 'Boots'],
    ['heels', 'Heels'],
    ['boot_worship', 'Boot / shoe worship'],
    ['socks_hosiery', 'Socks / hosiery'],
    ['gloves', 'Gloves'],
    ['corsetry', 'Corsetry / tightlacing vibe'],
    ['uniforms_gear', 'Uniforms / kit'],
    ['masks', 'Masks'],
    ['gas_mask_fetish', 'Gas mask fetish'],
    ['cigarette_ash', 'Ash / smoke play (venue & consent)'],
    ['food_play', 'Food play'],
    ['water_play_light', 'Water / splash play (non-edge)'],
    ['perfume_scent', 'Scent / perfume focus'],
    ['armpit_fetish', 'Armpit fetish'],
    ['hair_fetish', 'Hair fetish'],
    ['muscle_worship', 'Muscle worship'],
    ['belly_fetish', 'Belly fetish'],
    ['transformation_gear', 'Transformation / gear identity'],
    ['diaper_adult', 'Adult diaper / ABDL gear (adults only)'],
    ['sissy_feminization', 'Sissy / feminization (consensual)'],
    ['crossdressing_scene', 'Crossdressing in scene'],
    ['lingerie_forced', 'Lingerie / forced femme vibe'],
    ['suit_power', 'Suit / power-dressing energy'],
  ]),
  ...items('edge', [
    ['blood_play', 'Blood play (venue & skill gated)'],
    ['needle_play', 'Needle play (skill gated)'],
    ['staples', 'Staples / temporary body mod vibe'],
    ['sutures_play', 'Suture play (medical skill only)'],
    ['scalpel_play', 'Scalpel / cutting play (extreme skill)'],
    ['branding_play', 'Branding / intentional scar talk'],
    ['knife_play_real', 'Knife play with real edge risk'],
    ['gun_play_prop', 'Gun play with props only (never real firearms)'],
    ['cnc_negotiated', 'CNC / resist-ok (fully negotiated)'],
    ['noncon_roleplay', 'Non-con roleplay (scripted safeties)'],
    ['dubcon_energy', 'Dubcon energy (still fully consented)'],
    ['fear_play', 'Fear play'],
    ['interrogation', 'Interrogation (intense)'],
    ['abuse_roleplay', 'Abuse-roleplay aesthetics (consensual)'],
    ['domestic_violence_rp', 'DV-aesthetic roleplay (consensual, skilled)'],
    ['breath_play', 'Breath play (only with skilled partners)'],
    ['choking', 'Choking (explicit skill + consent)'],
    ['hand_over_mouth', 'Hand over mouth'],
    ['smothering_edge', 'Smothering (airway negotiated)'],
    ['waterboard_sim', 'Waterboard-style simulation'],
    ['drowning_sim', 'Drowning / pool edge sim (extreme skill)'],
    ['sounding', 'Sounding (skill + sterile practice)'],
    ['urethral_play', 'Urethral play'],
    ['catheter_play', 'Catheter play (medical skill)'],
    ['enema_play', 'Enemas'],
    ['watersports', 'Watersports / piss play'],
    ['golden_shower', 'Golden shower'],
    ['scat_play', 'Scat (rarely venue-ok)'],
    ['vomit_play', 'Vomit / emetophilia (rare; negotiate hard)'],
    ['race_play', 'Race play (only if both seek it)'],
    ['religious_blasphemy', 'Religious / blasphemy play'],
    ['political_taboo', 'Political / taboo ideology play'],
    ['ageplay_edge', 'Ageplay themes (adults only; negotiate hard)'],
    ['abdl_edge', 'ABDL scenes (adults only)'],
    ['incest_roleplay', 'Incest roleplay (adults; fantasy only)'],
    ['cheating_cuck_taboo', 'Cheating / betrayal fantasy'],
    ['snuff_fantasy', 'Snuff / death fantasy (fantasy talk only)'],
    ['torture_aesthetic', 'Torture-chamber aesthetic'],
    ['electro_edge', 'Heavy electro / violet extremes'],
    ['sleep_play', 'Sleep play / somno (prior consent + wake rules)'],
    ['drugged_fantasy', 'Drugged / incapacitated fantasy (no real drugs)'],
    ['consensual_nonconsent_abduction', 'Abduction CNC (public-safety rules)'],
    ['heavy_cbt', 'Heavy CBT'],
    ['ball_crushing', 'Ball crushing / pressing'],
    ['needle_genitals', 'Genital needles (extreme skill)'],
    ['hook_suspension', 'Hook / flesh-hook suspension (pro only)'],
    ['play_piercing', 'Play piercing'],
    ['scarification_talk', 'Scarification (permanent — discuss only)'],
  ]),
  ...items('social', [
    ['demo_teach', 'Demo / teach or learn'],
    ['skill_share', 'Skill share / technique talk'],
    ['audience_ok', 'Okay with an audience'],
    ['voyeur', 'Voyeur (watching others)'],
    ['exhibition', 'Exhibition (being watched)'],
    ['photo_consent', 'Photos only with explicit consent'],
    ['no_photos', 'No photos / recordings'],
    ['video_consent', 'Video only with explicit consent'],
    ['social_only', 'Mostly social — light or no scene'],
    ['short_scene', 'Short pickup scene'],
    ['longer_scene', 'Longer scene block'],
    ['group_scene', 'Group / more-than-two energy'],
    ['mmf_mfm', 'MMF / MFM energy'],
    ['ffm_fmf', 'FFM / FMF energy'],
    ['gangbang_energy', 'Gangbang / many-on-one energy'],
    ['bukkake_energy', 'Bukkake fantasy energy'],
    ['partner_share', 'Play while partner watches / joins'],
    ['public_dungeon', 'Open dungeon floor play'],
    ['private_corner', 'Quieter / more private corner'],
    ['aftercare_public', 'Aftercare okay in the room'],
    ['debrief_same_night', 'Debrief same night'],
    ['topping_from_bottom_ok', 'Okay with topping-from-bottom energy'],
    ['switch_mid_scene', 'Switch mid-scene'],
    ['service_topping', 'Service topping'],
    ['sadistic_topping', 'Sadistic topping'],
    ['masochistic_bottoming', 'Masochistic bottoming'],
    ['pillow_princess', 'Pillow princess / receive-focused'],
    ['generous_top', 'Generous / pleasure-focused topping'],
  ]),
]

export const CATALOG_BY_ID: Record<string, CatalogItem> = Object.fromEntries(
  PICKUP_PLAY_CATALOG.map((i) => [i.id, i]),
)

/**
 * “I want the scene to feel…” — emotional tone / headspace chips.
 * Inspired by common negotiation prompts (desired feelings, tone, headspace)
 * from kink education; original labels for kink.social — not a copy of any list.
 */
export const PICKUP_PLAY_FEELINGS = [
  // Tone & vibe
  { id: 'playful', label: 'Playful' },
  { id: 'silly', label: 'Silly / bratty fun' },
  { id: 'teasing', label: 'Teasing / mischievous' },
  { id: 'sensual', label: 'Sensual' },
  { id: 'erotic', label: 'Erotic' },
  { id: 'romantic', label: 'Romantic / tender' },
  { id: 'nurturing', label: 'Nurturing / caring' },
  { id: 'soft_gentle', label: 'Soft / gentle' },
  { id: 'strict', label: 'Strict / mean (consensual)' },
  { id: 'intense', label: 'Intense / high-voltage' },
  { id: 'low_key', label: 'Low-key / chill' },
  { id: 'serious', label: 'Serious / focused' },
  { id: 'ritual_feel', label: 'Ritual / ceremonial' },
  { id: 'celebratory', label: 'Celebratory / fun night' },
  // Power & role energy
  { id: 'dominant', label: 'Dominant' },
  { id: 'submissive', label: 'Submissive' },
  { id: 'controlled', label: 'Controlled' },
  { id: 'helpless', label: 'Helpless' },
  { id: 'powerful', label: 'Powerful' },
  { id: 'obedient', label: 'Obedient' },
  { id: 'owned_feel', label: 'Owned (scene-scoped)' },
  { id: 'protected', label: 'Protected / held' },
  { id: 'useful', label: 'Useful / of service' },
  { id: 'used_feel', label: 'Used (consensual, scene-scoped)' },
  { id: 'disciplined', label: 'Disciplined / corrected' },
  { id: 'punished', label: 'Punished (consensual frame)' },
  { id: 'sadistic', label: 'Sadistic' },
  { id: 'masochistic', label: 'Masochistic' },
  // Warmth & regard
  { id: 'worshipped', label: 'Worshipped / adored' },
  { id: 'cherished', label: 'Cherished / precious' },
  { id: 'beautiful', label: 'Beautiful / seen' },
  { id: 'admired', label: 'Admired / respected' },
  { id: 'spoiled', label: 'Spoiled / pampered' },
  { id: 'needed', label: 'Needed / wanted' },
  { id: 'connected', label: 'Connected / intimate' },
  { id: 'platonic', label: 'Platonic connection' },
  // Altered / release headspaces
  { id: 'peaceful', label: 'Peaceful / floaty' },
  { id: 'subspacey', label: 'Subspacey / trancey' },
  { id: 'topspace', label: 'Topspace / flow (for tops)' },
  { id: 'meditative', label: 'Meditative / blank mind' },
  { id: 'euphoric', label: 'Euphoric' },
  { id: 'catharsis', label: 'Catharsis / emotional purge' },
  { id: 'released', label: 'Released / unburdened' },
  { id: 'overwhelmed', label: 'Overwhelmed' },
  { id: 'grounded', label: 'Grounded / present' },
  // Edge emotions (still negotiated, consensual)
  { id: 'degraded', label: 'Degraded (consensual)' },
  { id: 'humiliated', label: 'Humiliated (consensual)' },
  { id: 'objectified_feel', label: 'Objectified (consensual)' },
  { id: 'shamed', label: 'Shamed (consensual play)' },
  { id: 'guilty_play', label: 'Guilty / atoning (play frame)' },
  { id: 'scared_safe', label: 'Scared-but-safe' },
  { id: 'prey_feel', label: 'Prey / hunted energy' },
  { id: 'small_feel', label: 'Small / tiny (consensual)' },
  { id: 'exposed_feel', label: 'Exposed / on display' },
  { id: 'filthy_feel', label: 'Filthy / slutty (consensual)' },
  // Challenge & wildness
  { id: 'challenged', label: 'Challenged / pushed' },
  { id: 'endurance', label: 'Endurance / trial' },
  { id: 'victorious', label: 'Victorious / I took it' },
  { id: 'primal_feel', label: 'Primal' },
  { id: 'wild', label: 'Wild / uninhibited' },
  { id: 'free_feel', label: 'Free / shameless' },
  { id: 'energetic', label: 'Energetic / athletic' },
  { id: 'surprised', label: 'Surprised (within negotiated envelope)' },
  // Meta / pickup context
  { id: 'technical_mood', label: 'Technical / craft-focused' },
  { id: 'performative', label: 'Performative / for an audience' },
  { id: 'curious', label: 'Curious / exploratory' },
  { id: 'aftercare_mood', label: 'Aftercare-forward' },
  { id: 'social_mood', label: 'Social first, play maybe' },
] as const

/** Aftercare chips — physical, emotional, erotic cool-down, and logistics. */
export const PICKUP_PLAY_AFTERCARE = [
  // Basics
  { id: 'water', label: 'Water / electrolytes' },
  { id: 'snack', label: 'Snack / sugar / salt' },
  { id: 'blanket', label: 'Blanket / warmth' },
  { id: 'cool_compress', label: 'Cool cloth / ice pack' },
  { id: 'shower', label: 'Shower / wipe-down help' },
  { id: 'clothes', label: 'Help with clothes / cleanup' },
  // Touch & affection
  { id: 'cuddle', label: 'Cuddling / hold me' },
  { id: 'kisses', label: 'Kisses / soft makeouts' },
  { id: 'gentle_massage', label: 'Gentle massage' },
  { id: 'hair_stroke', label: 'Hair stroking / scalp rub' },
  { id: 'hand_holding', label: 'Hand-holding' },
  { id: 'lap_time', label: 'Sit in lap / be held' },
  // Space & recovery
  { id: 'space', label: 'Space / leave me be' },
  { id: 'alone_ok', label: 'Solo cool-down is fine' },
  { id: 'nap', label: 'Nap / quiet rest' },
  { id: 'grounding', label: 'Grounding (name 5 things, etc.)' },
  { id: 'music_soft', label: 'Soft music / low stimulation' },
  { id: 'dim_lights', label: 'Dim lights / less crowd' },
  // Talk & check-ins
  { id: 'talk', label: 'Quiet conversation' },
  { id: 'debrief', label: 'Verbal debrief soon' },
  { id: 'praise_after', label: 'Reassurance / praise' },
  { id: 'no_debrief_yet', label: 'No deep debrief yet — later' },
  { id: 'checkin_tmrw', label: 'Check-in tomorrow (text ok)' },
  { id: 'checkin_same_night', label: 'Check-in later tonight' },
  // Social re-entry
  { id: 'socialize', label: 'Ease back into the room' },
  { id: 'stay_nearby', label: 'Stay nearby but don’t hover' },
  { id: 'walk_me', label: 'Walk me to next spot / exit' },
  { id: 'service_after', label: 'Light service / caretaking' },
  { id: 'top_drop_care', label: 'Care for the top / switch too' },
  // Erotic aftercare (still negotiated)
  { id: 'aftercare_sex', label: 'Sex as aftercare' },
  { id: 'aftercare_masturbate_me', label: 'Be masturbated / brought off gently' },
  { id: 'aftercare_i_masturbate', label: 'I want to masturbate them / get them off' },
  { id: 'aftercare_oral', label: 'Gentle oral as aftercare' },
  { id: 'aftercare_orgasm', label: 'An orgasm to land' },
  { id: 'aftercare_no_sex', label: 'No sexual contact in aftercare' },
  { id: 'aftercare_tease_soft', label: 'Soft teasing / sensual touch only' },
  // Practical
  { id: 'mark_check', label: 'Check marks / skin together' },
  { id: 'gear_pack', label: 'Help pack gear' },
  { id: 'photo_marks_private', label: 'Private mark photos (consent)' },
] as const

/**
 * “I prefer to play with…” — inclusive partner filters for the deck.
 * Multi-select; “Anyone” means no gender filter.
 */
export const PICKUP_PLAY_WITH = [
  { id: 'anyone', label: 'Anyone / no gender filter' },
  { id: 'men', label: 'Men / masculine-identifying folks' },
  { id: 'women', label: 'Women / feminine-identifying folks' },
  { id: 'nonbinary', label: 'Non-binary folks' },
  { id: 'trans_masc', label: 'Trans men / transmasculine folks' },
  { id: 'trans_fem', label: 'Trans women / transfeminine folks' },
  { id: 'amab', label: 'AMAB folks' },
  { id: 'afab', label: 'AFAB folks' },
  { id: 'intersex', label: 'Intersex folks' },
  { id: 'queer_gender', label: 'Queer / gender-expansive folks' },
  { id: 'bi_curious_partners', label: 'Bi / bicurious partners' },
  { id: 'open_exploring', label: 'Open / still exploring' },
  { id: 'discuss_gender', label: 'Prefer to discuss in person' },
] as const

/**
 * “For matching tonight, I show up as…” — scene-scoped self tags so others’ filters work.
 * Does not rewrite your profile; only used for this matchmaker.
 */
export const PICKUP_PLAY_I_AM = [
  { id: 'man', label: 'Man / masculine' },
  { id: 'woman', label: 'Woman / feminine' },
  { id: 'nonbinary', label: 'Non-binary' },
  { id: 'trans_man', label: 'Trans man / transmasculine' },
  { id: 'trans_woman', label: 'Trans woman / transfeminine' },
  { id: 'amab', label: 'AMAB' },
  { id: 'afab', label: 'AFAB' },
  { id: 'intersex', label: 'Intersex' },
  { id: 'genderfluid', label: 'Genderfluid / questioning' },
  { id: 'queer_gender', label: 'Queer / gender-expansive' },
  { id: 'prefer_not', label: 'Prefer not to say for matching' },
] as const

/**
 * Sexual-health risk profile for matching — alike / acceptable risk, not stigma.
 * Pick what fits how you want to negotiate risk with partners.
 */
export const PICKUP_PLAY_STI_RISK = [
  {
    id: 'discuss_before',
    label: 'Discuss before sexual play',
    hint: 'Status, barriers, and risk talk before fluids / genital contact.',
  },
  {
    id: 'prefer_recent_clear',
    label: 'Prefer recent clear panel',
    hint: 'Matching leans toward folks with a recent negative panel across the board.',
  },
  {
    id: 'hsv1_informed_ok',
    label: 'HSV-1 informed & open',
    hint: 'I understand oral HSV-1 / cold-sore risk and can still play when we talk it through.',
  },
  {
    id: 'hsv2_informed_ok',
    label: 'HSV-2 informed & open',
    hint: 'I know the risks of playing with someone who has HSV-2 antibodies when we’re informed.',
  },
  {
    id: 'hiv_uu_ok',
    label: 'HIV U=U understood',
    hint: 'I understand undetectable = untransmittable in context and will discuss as needed.',
  },
  {
    id: 'barriers_default',
    label: 'Barriers by default',
    hint: 'Condoms / dams for penetrative or fluid-risk play unless we renegotiate.',
  },
  {
    id: 'fluid_after_talk',
    label: 'Fluid exchange only after risk talk',
    hint: 'Open to fluids when we’ve aligned on risk — not casually.',
  },
  {
    id: 'same_profile_prefer',
    label: 'Prefer similar risk posture',
    hint: 'Match me with people whose STI / risk chips look like mine.',
  },
  {
    id: 'skip_nonsexual',
    label: 'N/A — non-sexual play',
    hint: 'Skipped when both sides are here for non-sexual play.',
  },
] as const
