/** Curated relationship labels - users can also enter a custom label. */
export const PROFILE_RELATIONSHIP_LABELS: readonly string[] = [
  'Single',
  'Dating',
  'Crushing on',
  'Courting',
  'Partner',
  'Life partner',
  'Girlfriend',
  'Boyfriend',
  'Theyfriend',
  'Joyfriend',
  'Spouse',
  'Husband',
  'Wife',
  'Engaged to',
  'Married to',
  'Handfasted with',
  'Exclusive with',
  'In a relationship with',
  'Long-distance relationship with',
  'In love with',
  'Intimate with',
  'Lover of',
  'Companion of',
  'Best friend of',
  'Platonic partner of',
  'Queer platonic partner of',
  'Soulmate of',
  'Friend with benefits with',
  'Play partner with',
  'Monogamous with',
  'Monogamish with',
  'Non-monogamous with',
  'Open with',
  'Open relationship with',
  'Polyamorous with',
  'Solo polyamorous',
  'Polycurious',
  'Triad with',
  'Throuple with',
  'Primary partner',
  'Secondary partner',
  'Nesting partner',
  'Anchor partner',
  'Metamour of',
  'Comet relationship with',
  'Situationship with',
  "It's complicated with",
  'Relationship anarchy with',
  'Chosen family with',
  'Member of a house with',
  'Leather family with',
  'Rope family with',
  'Poly family with',
  'Separated from',
  'Divorced from',
  'Surviving partner of',
] as const

/** Curated D/s dynamic labels - custom labels allowed. */
export const PROFILE_DS_RELATIONSHIP_LABELS: readonly string[] = [
  'Dominant to',
  'Domme to',
  'Domina to',
  'Daddy Dom to',
  'Master to',
  'Mistress to',
  'Sir to',
  'Ma\'am to',
  'Owner to',
  'Co-owner of',
  'Handler to',
  'Rigger to',
  'Submissive to',
  'submissive to',
  'slave to',
  'Owned by',
  'Collared by',
  'Property of',
  'Service submissive to',
  'Pet of',
  'Rope bottom to',
  'Knight of',
  'Switches with',
  'Switch with',
  'Dom-leaning switch with',
  'Sub-leaning switch with',
  'Brat tamer to',
  'Brat of',
  'Gorean with',
  'Educator to',
  'Vetted by',
  'unowned',
  'unpartnered',
  'unclaimed',
  'Presently inactive',
  'Not applicable',
] as const

export const PROFILE_RELATIONSHIP_LABEL_MAX = 128 as const
export const PROFILE_RELATIONSHIP_CUSTOM_TEXT_MAX = 2000 as const

export function filterRelationshipLabelSuggestions(
  query: string,
  suggestions: readonly string[],
  limit = 12
): string[] {
  const q = query.trim().toLowerCase()
  const pool = q ?
      suggestions.filter((s) => s.toLowerCase().includes(q))
    : [...suggestions]
  return pool.slice(0, limit)
}
