export const LIFESTYLE_ACTIVITY_OPTIONS: readonly string[] = [
  'Curious / exploring',
  'New to the scene',
  'Occasional participant',
  'Regular scene-goer',
  'Part-time / scene only',
  'Full-time lifestyle',
  '24/7 dynamic',
  'Bedroom only',
  'Events & munches only',
  'Online / long-distance',
  'Mostly social',
  'Mostly educational',
  'Mentor / educator active',
  'Returning after break',
  'On hiatus',
  'Private / discreet',
  'Seasonal / travel-based',
  'Professional (performer / educator)',
] as const
